#!/usr/bin/env python3
"""Render the committed PDFs -- Markdown docs with code lines that WRAP, plus the deck.

Replaces the manual "preview in VS Code, print from the browser" flow. Same engine as
before -- headless Chrome, so the committed PDFs stay Skia-produced -- but the styling is
ours and checked in, so two people regenerating the same source get the same file.

    python3 reference/gen_pdf.py                       # every pair in PAIRS below
    python3 reference/gen_pdf.py docs/DEVELOPER_GUIDE.md
    python3 reference/gen_pdf.py docs/foo.md -o /tmp/foo.pdf

Two pipelines, picked by extension:
  .md   -> pandoc (GFM -> HTML5, with highlighting) -> our CSS -> Chrome --print-to-pdf
  .pptx -> LibreOffice --convert-to pdf  (docs/AutoBench.pptx, itself generated by
           docs/generate_pptx.py -- run that first if the slide content changed)

THE POINT OF THE CSS: a long shell command must never be clipped at the page edge. Three
rules do that, and they are the reason this file exists rather than a one-line pandoc call:

  1. `pre { white-space: pre-wrap }`   -- wrap instead of overflowing.
  2. a hanging indent per LOGICAL line -- pandoc wraps each source line in its own
     `<span id="cbN-M">`, so continuation rows sit indented under their own line and you
     can still see where one command ends and the next begins. Without this, a wrapped
     `export FOO=...` is indistinguishable from two separate commands, which is exactly
     how the old browser-printed PDFs read.
  3. `overflow-wrap: anywhere` on code and table cells -- URLs and flag soup have no
     spaces to break at, so without this the browser refuses to wrap them at all.

Requires: pandoc and Google Chrome (for .md), LibreOffice (for .pptx). All external
binaries; there is no Python dependency, so this runs from a bare checkout. A tool is only
looked for if a source needs it.
"""

from __future__ import annotations

import argparse
import html
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import time

REPO = pathlib.Path(__file__).resolve().parent.parent

# The docs that ship a committed PDF beside their .md. Add a pair here and it is picked up
# by a bare `python3 reference/gen_pdf.py`.
PAIRS = [
    ("docs/DEVELOPER_GUIDE.md", "docs/DEVELOPER_GUIDE.pdf"),
    ("docs/12_RUNS_CROSS_CLUSTER.md", "docs/12_RUNS_CROSS_CLUSTER.pdf"),
    ("docs/AutoBench.pptx", "docs/AutoBench.pdf"),
]

SOFFICE_CANDIDATES = ["/Applications/LibreOffice.app/Contents/MacOS/soffice"]

# A table cell longer than this is allowed to break mid-word (`.wrapany`). Below it, the
# cell keeps its natural min-content width so narrow columns stay narrow.
WIDE_CELL_CHARS = 60

CHROME_CANDIDATES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
]

CSS = r"""
@page { size: A4; margin: 16mm 14mm 16mm 14mm; }

html { -webkit-print-color-adjust: exact; print-color-adjust: exact; }

body {
  font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
  font-size: 10.5pt; line-height: 1.55; color: #1f2328;
  margin: 0; padding: 0;
}

/* ---- headings ------------------------------------------------------------ */
h1, h2, h3, h4, h5, h6 { line-height: 1.25; margin: 1.4em 0 .5em; font-weight: 600;
                         break-after: avoid; -webkit-column-break-after: avoid; }
h1 { font-size: 20pt; padding-bottom: .25em; border-bottom: 1px solid #d1d9e0; }
h2 { font-size: 15pt; padding-bottom: .25em; border-bottom: 1px solid #d1d9e0; }
h3 { font-size: 12.5pt; }
h4 { font-size: 11pt; }
h1:first-of-type { margin-top: 0; }

p, ul, ol, table, pre, blockquote { margin: 0 0 .8em; }
li { margin: .15em 0; }
li > p { margin: .3em 0; }
a { color: #0969da; text-decoration: none; }

hr { border: 0; border-top: 1px solid #d1d9e0; margin: 1.4em 0; }

blockquote {
  margin-left: 0; padding: .1em 0 .1em 1em;
  border-left: .25em solid #d1d9e0; color: #59636e;
}
blockquote > :last-child { margin-bottom: 0; }

/* ---- code: the wrapping rules ------------------------------------------- */
code, kbd, samp, pre {
  font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
}

/* inline code */
:not(pre) > code {
  font-size: .875em; padding: .15em .35em; border-radius: 5px;
  background: #eff1f3; overflow-wrap: anywhere;
}

pre {
  font-size: 8.6pt; line-height: 1.45;
  padding: .7em .85em; border-radius: 6px;
  background: #f6f8fa; border: 1px solid #d1d9e0;
  /* (1) wrap rather than clip at the page edge */
  white-space: pre-wrap;
  /* (3) break inside unbroken URLs / flag soup, which have nowhere else to break */
  overflow-wrap: anywhere; word-break: break-word;
  break-inside: auto;
}
pre > code { padding: 0; background: none; border: 0; font-size: inherit;
             white-space: inherit; overflow-wrap: inherit; }

/* (2) hanging indent per LOGICAL source line.
   pandoc emits one <span id="cbN-M"> per line for highlighted blocks; gen_pdf.py adds
   <span class="cl"> for unhighlighted ones. Either way each logical line is a block, so a
   wrapped continuation is visibly indented under its own line instead of looking like a
   new command. */
pre > code > span[id^="cb"], pre > code > span.cl {
  display: block; padding-left: 3.2ch; text-indent: -3.2ch;
}
/* a blank line must still occupy a row */
pre > code > span[id^="cb"]:empty::after,
pre > code > span.cl:empty::after { content: "\200b"; }
/* pandoc's per-line anchors are decorative; keep them from adding width */
pre > code > span[id^="cb"] > a:first-child { display: none; }

/* skylighting token colours (GitHub-light-ish), trimmed to what our docs use */
code span.kw { color: #cf222e; }                    /* keyword */
code span.cf { color: #cf222e; }                    /* control flow */
code span.bu, code span.ex { color: #8250df; }      /* builtin / external cmd */
code span.st { color: #0a3069; }                    /* string */
code span.va { color: #953800; }                    /* variable */
code span.dv, code span.dt { color: #0550ae; }      /* value / datatype */
code span.at { color: #0550ae; }                    /* attribute (long flags) */
code span.op { color: #0550ae; }                    /* operator */
code span.co { color: #59636e; font-style: italic; }/* comment */
code span.fu { color: #8250df; }                    /* function */
code span.er, code span.al { color: #cf222e; }      /* error / alert */

/* ---- tables: same problem, same fix ------------------------------------- */
table {
  border-collapse: collapse; width: 100%;
  table-layout: auto; font-size: 9pt;
}
th, td {
  border: 1px solid #d1d9e0; padding: .35em .5em; text-align: left;
  vertical-align: top;
  /* Break inside over-long words, but only at a *line* level: `overflow-wrap: break-word`
     leaves a column's min-content width alone. NOT `anywhere` and NOT
     `word-break: break-word` (Chrome implements that as `anywhere`) -- either one shrinks
     min-content to a single character, and the auto table layout then squeezes the "#"
     column until "11" stacks as 1/1 and the "Code" header splits into "Cod/e". */
  overflow-wrap: break-word;
}
/* Cells that really are long -- the §6.5 commands run to 190 chars with no spaces late in
   the string -- opt in to breaking anywhere. gen_pdf.py tags them by measured text length,
   so short cells never pay the min-content cost above. */
th.wrapany, td.wrapany { overflow-wrap: anywhere; }
th { background: #f6f8fa; font-weight: 600; }
/* keep a row intact across a page break where possible */
tr { break-inside: avoid; }
thead { display: table-header-group; }
table code { background: none; padding: 0; font-size: .95em; }

img { max-width: 100%; }
"""

HTML_SHELL = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>{title}</title>
<style>{css}</style>
</head><body>
{body}
</body></html>
"""


def find_chrome() -> str:
    for c in CHROME_CANDIDATES:
        if pathlib.Path(c).is_file():
            return c
    for n in ("chromium", "google-chrome", "google-chrome-stable"):
        p = shutil.which(n)
        if p:
            return p
    sys.exit("no Chrome/Chromium found; install Google Chrome or set one of "
             + ", ".join(CHROME_CANDIDATES))


def find_soffice() -> str:
    for c in SOFFICE_CANDIDATES:
        if pathlib.Path(c).is_file():
            return c
    for n in ("soffice", "libreoffice"):
        p = shutil.which(n)
        if p:
            return p
    sys.exit("no LibreOffice found (needed for .pptx); install it or drop the pptx pair")


def render_pptx(src: pathlib.Path, pdf_path: pathlib.Path, soffice: str,
                timeout: int = 300) -> None:
    """Slides -> PDF via LibreOffice. It insists on naming the output itself (<stem>.pdf in
    --outdir), so convert into a temp dir and move the result to the path we were asked for."""
    with tempfile.TemporaryDirectory() as td:
        tmp = pathlib.Path(td)
        subprocess.run([soffice, "--headless", f"-env:UserInstallation={(tmp / 'profile').as_uri()}",
                        "--convert-to", "pdf", "--outdir", str(tmp), str(src)],
                       check=True, capture_output=True, text=True, timeout=timeout)
        produced = tmp / (src.stem + ".pdf")
        if not produced.is_file():
            sys.exit(f"libreoffice produced no PDF for {src}")
        pdf_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(produced), str(pdf_path))
    print(f"{src} -> {pdf_path}  ({pdf_path.stat().st_size:,} bytes)")


def md_to_html_body(md: pathlib.Path) -> str:
    """GFM -> HTML fragment, highlighted, with per-line spans everywhere."""
    out = subprocess.run(
        ["pandoc", "--from", "gfm", "--to", "html5", "--wrap=preserve", str(md)],
        check=True, capture_output=True, text=True).stdout

    # pandoc separates its per-line spans with a real newline. Under `white-space:
    # pre-wrap` that newline renders as a break IN ADDITION to the span's display:block,
    # which double-spaces every code block. Drop exactly those newlines.
    out = re.sub(r'</span>\n(?=<span id="cb)', "</span>", out)

    # Fenced blocks with no language get no per-line spans from pandoc, so add them --
    # otherwise those blocks lose the hanging indent and wrap ambiguously.
    def add_line_spans(m: re.Match) -> str:
        open_tag, body = m.group(1), m.group(2)
        if "<span" in body:                       # already highlighted; leave alone
            return m.group(0)
        lines = body.split("\n")
        if lines and lines[-1] == "":
            lines.pop()
        return open_tag + "".join(f'<span class="cl">{l}</span>' for l in lines) + "</code></pre>"

    out = re.sub(r'(<pre[^>]*><code[^>]*>)(.*?)</code></pre>', add_line_spans, out,
                 flags=re.S)

    # Tag long table cells so the CSS can let them break mid-word without narrowing every
    # other column (see the `.wrapany` rule).
    def tag_wide_cell(m: re.Match) -> str:
        tag, attrs, inner = m.group(1), m.group(2), m.group(3)
        text = html.unescape(re.sub(r"<[^>]+>", "", inner))
        if len(text.strip()) <= WIDE_CELL_CHARS:
            return m.group(0)
        if 'class="' in attrs:
            attrs = attrs.replace('class="', 'class="wrapany ', 1)
        else:
            attrs += ' class="wrapany"'
        return f"<{tag}{attrs}>{inner}</{tag}>"

    out = re.sub(r"<(t[dh])((?:\s[^>]*)?)>(.*?)</\1>", tag_wide_cell, out, flags=re.S)
    return out


def render(md_path: pathlib.Path, pdf_path: pathlib.Path, chrome: str,
           timeout: int = 90) -> None:
    body = md_to_html_body(md_path)
    title = md_path.stem
    doc = HTML_SHELL.format(title=html.escape(title), css=CSS, body=body)

    with tempfile.TemporaryDirectory() as td:
        tmp = pathlib.Path(td)
        html_file = tmp / f"{title}.html"
        html_file.write_text(doc, encoding="utf-8")
        pdf_path.parent.mkdir(parents=True, exist_ok=True)
        cmd = [
            chrome,
            "--headless=new",
            "--disable-gpu",
            # never touch the user's real Chrome profile
            f"--user-data-dir={tmp / 'profile'}",
            "--no-first-run", "--no-default-browser-check",
            "--no-pdf-header-footer",
            "--run-all-compositor-stages-before-draw",
            "--virtual-time-budget=20000",
            f"--print-to-pdf={pdf_path}",
            html_file.as_uri(),
        ]
        before = pdf_path.stat().st_mtime_ns if pdf_path.is_file() else -1
        # Headless Chrome writes the PDF in a few seconds and then does NOT exit -- waiting
        # on the process turns a 6-second render into a 90-second one. So watch the artifact
        # instead: as soon as it is rewritten and its size has stopped growing, we have what
        # we came for and Chrome can be killed.
        proc = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        deadline, last_size, done = time.monotonic() + timeout, None, False
        while time.monotonic() < deadline:
            if proc.poll() is not None:          # exited on its own; artifact is final
                done = True
                break
            st = pdf_path.stat() if pdf_path.is_file() else None
            if st and st.st_mtime_ns != before:
                if st.st_size == last_size and st.st_size > 0:
                    done = True
                    break
                last_size = st.st_size
            time.sleep(0.3)
        if proc.poll() is None:
            proc.kill()
        proc.wait()
        if not done or not pdf_path.is_file() or pdf_path.stat().st_mtime_ns == before:
            sys.exit(f"chrome produced no PDF for {md_path} within {timeout}s")
    size = pdf_path.stat().st_size
    print(f"{md_path} -> {pdf_path}  ({size:,} bytes)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("sources", nargs="*",
                    help="markdown files; default is every pair listed in PAIRS")
    ap.add_argument("-o", "--output", help="output PDF (only with a single source)")
    ap.add_argument("--timeout", type=int, default=90,
                    help="seconds to wait for Chrome before killing it (default 90)")
    a = ap.parse_args()

    if a.sources:
        if a.output and len(a.sources) > 1:
            sys.exit("--output takes a single source")
        jobs = [(pathlib.Path(s), pathlib.Path(a.output) if a.output
                 else pathlib.Path(s).with_suffix(".pdf")) for s in a.sources]
    else:
        jobs = [(REPO / m, REPO / p) for m, p in PAIRS]

    for src, pdf in jobs:
        if not src.is_file():
            sys.exit(f"missing source: {src}")

    # Resolve each toolchain only if something in this batch needs it, so a machine without
    # LibreOffice can still regenerate the markdown PDFs and vice versa.
    slides = [j for j in jobs if j[0].suffix.lower() == ".pptx"]
    docs = [j for j in jobs if j[0].suffix.lower() != ".pptx"]
    if docs:
        if not shutil.which("pandoc"):
            sys.exit("pandoc not found; brew install pandoc")
        chrome = find_chrome()
        for md, pdf in docs:
            render(md, pdf, chrome, a.timeout)
    if slides:
        soffice = find_soffice()
        for src, pdf in slides:
            render_pptx(src, pdf, soffice)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
